### ISSUE TITLE
Implement Artificial Player createMove(gameState) function.

### ISSUE THREAD

**Issue by SWhelan** [SWhelan/cardswithfriends#4]
I think this is all that will need to happen to get artificial players to work with the rest of the system. Not necessary for the demo on friday but just to use the issue tracker as a way to remember what all we have to do.

**Comment by ghodulik95** [comment]
Parameters were changed from gameState to the piles ai has access too.

**Comment by SWhelan** [comment]
This is implemented and working very well. 

If any further enhancements should be made to the artificial player (making them smarter/providing levels of AI) put that in a different issue as that will likely require other changes like providing a way to choose levels of AIs on the front end etc.
